project:
  type: website
  output-dir: docs

website:
  title: "blogQuarto"
  navbar:
    right:
      - about.qmd

format:
  html:
    theme: solar
    css: styles.css

editor: visual

